from enum import Enum

class Countries(Enum):
    ITA = 'איטליה'
    TUR = 'טורקיה'
    SUI = 'שווייץ'
    WAL = 'וויילס'
    BEL = 'בלגיה'
    DEN = 'דנמרק'
    FIN = 'פינלנד'
    RUS = 'רוסיה'
    AUT = 'אוסטריה'
    NED = 'הולנד'
    MKD = 'צפון מקדוניה'
    UKR = 'אוקראינה'
    CRO = 'קרואטיה'
    CZE = 'צ`כיה'
    ENG = 'אנגליה'
    SCO = 'סקוטלנד'
    POL = 'פולין'
    SVK = 'סלובקיה'
    ESP = 'ספרד'
    SWE = 'שבדיה'
    FRA = 'צרפת'
    GER = 'גרמניה'
    HUN = 'הונגריה'
    POR = 'פורטוגל'
